### ISSUE TITLE
能否在MethodContext中扩展一个Dictionary的用户附加数据属性？

### ISSUE THREAD

**Issue by dboydboy** [inversionhourglass/Rougamo#10]
能否在MethodContext中扩展一个Dictionary的用户附加数据属性？
例如
Dictionary<string, object> AdditionalData
可以允许用户添加自己的数据，并可以在前后Attribute中传递?

**Comment by inversionhourglass** [comment]
你说的前后`Attribute`是指一个方法应用多个`Attribute`时，这些`Attribute`之间传递是吗？如果是这个，可以增加

**Comment by dboydboy** [comment]
> 你说的前后`Attribute`是指一个方法应用多个`Attribute`时，这些`Attribute`之间传递是吗？如果是这个，可以增加

是的，希望在一个方法的多个Attribute之间能有个传递自定义数据的方法

**Comment by inversionhourglass** [comment]
https://github.com/inversionhourglass/Rougamo/blob/47f8068e8fb7cc15ecb9c644fe3f0bc0d11abd7e/src/Rougamo/Context/MethodContext.cs#L28

新增了一个`object`类型的`Data`属性，默认值`null`，如果你希望使用`Dictionary<string, object>`可以自己转换一下，已发布`1.1.1-beta`版本，正式版会晚些天再发

**Comment by inversionhourglass** [comment]
https://github.com/inversionhourglass/Rougamo/blob/d948ecf6481dcf0cd5bb731d3be31e0054af1f22/src/Rougamo/Context/MethodContext.cs#L37

在`1.1.2`版本里新增了一个`IDictionary`类型的`Datas`属性，之前还是没有考虑周到，`object`类型的`Data`属性在多个开发者使用Rougamo开发不同组件时如果不是提前沟通如何使用`Data`属性，那么就很容易造成互相覆盖，现在增加`IDictionary`类型属性来解决这个问题，`Data`属性在`1.1.2`之后被标记为`Obsolete`
