### ISSUE TITLE
请问能否在OnEntry方法中实现对实际方法调用的拦截？

### ISSUE THREAD

**Issue by SeptSky** [inversionhourglass/Rougamo#12]
你好！
   新的版本实现了对异常抛出的控制，目前使用体验非常好，再次感谢！

   我在考虑授权问题时，想通过添加Attribute的方式对指定的方法进行授权认证，满足授权认证则进行实际方法的调用，如果不满足则禁止方法的调用，对于有返回值的方法直接返回对应类型的默认值。虽然使用Castle的方法代理也能实现，但感觉还是使用你的Rougamo方式更加简单方便。不知这种方法拦截能否实现？

谢谢！

**Comment by inversionhourglass** [comment]
在`OnEntry`和`OnSuccess`可以通过`MethodContext.ReplaceReturnValue(IMo, object)`修改/设置返回值，可以参考 [这里的代码](https://github.com/inversionhourglass/Rougamo/blob/06fccba8537874580f69c26b5b53fb70d5fdcb5f/test/TestAssemblies/BasicUsage/Attributes/SyncEntryModifierAttribute.cs#L9-L21)

关于你说的希望“对有返回值的方法直接返回对应类型的默认值”，你可以通过`MethodContext.RealReturnType`获取到方法的返回值，关于如何通过`Type`对象获取该类型对应的默认值，如果想找一个比较高效率或者方便的方式，你可以从StackOverflow的 [这个问题](https://stackoverflow.com/questions/325426/programmatic-equivalent-of-defaulttype) 里找到不同版本的方法，希望对你有所帮助

**Comment by SeptSky** [comment]
简单测试了一下，ReplaceReturnValue确实能够拦截实际方法的调用，完美！
