### ISSUE TITLE
能否提供异步拦截方法, 如OnEntryAsync

### ISSUE THREAD

**Issue by q7164518** [inversionhourglass/Rougamo#13]
如题, 大佬能否提供几个拦截函数的异步方法

**Comment by inversionhourglass** [comment]
这个功能之前有考虑过，不过考虑到下面这个问题：

有异步的需求一般是不希望在现在`OnEntry`此类方法中同步阻塞异步代码，但同样的，在实现异步`Attribute`之后，如果将异步`Attribute`应用在同步方法上，那么织入的异步代码将不得不同步阻塞执行。当然也可以在编译是检查异步`Attribute`不可应用于同步方法，但这样做就会大大减小易用性，不是一种好的方式。

一般方法级别的AOP操作期望是织入轻逻辑低成本低耗时的代码，所以一般是不推荐异步执行一些耗时较久的操作，而如果确定是低耗时的异步操作，可以考虑直接同步阻塞执行。

另外异步代码的织入实现可能会比较麻烦，在考虑到上面两点的情况下，暂时没有实现异步`Attribute`的计划。

**Comment by q7164518** [comment]
> 这个功能之前有考虑过，不过考虑到下面这个问题：
> 
> 有异步的需求一般是不希望在现在`OnEntry`此类方法中同步阻塞异步代码，但同样的，在实现异步`Attribute`之后，如果将异步`Attribute`应用在同步方法上，那么织入的异步代码将不得不同步阻塞执行。当然也可以在编译是检查异步`Attribute`不可应用于同步方法，但这样做就会大大减小易用性，不是一种好的方式。
> 
> 一般方法级别的AOP操作期望是织入轻逻辑低成本低耗时的代码，所以一般是不推荐异步执行一些耗时较久的操作，而如果确定是低耗时的异步操作，可以考虑直接同步阻塞执行。
> 
> 另外异步代码的织入实现可能会比较麻烦，在考虑到上面两点的情况下，暂时没有实现异步`Attribute`的计划。

好的, 明白

**Comment by q7164518** [comment]
😊
