### ISSUE TITLE
对 Task 非 async 方法的拦截问题

### ISSUE THREAD

**Issue by 2881099** [inversionhourglass/Rougamo#14]
```c#
[Transactional]
public Task InsertTest()
{
    return Task.Delay(TimeSpan.FromSeconds(10)).ContinueWith(t => 
        _repoSong.InsertAsync(new Song()));
}

public class TransactionalAttribute : Rougamo.MoAttribute
{
    //...
}
```

感觉作者提供这么方便的组件。

上面 InsertTest 方法没有标记 async，当进入 OnExit 的时候会清除 _repo.UnitOfWork 状态，但是 _repo.InsertAsync 插入并未完成。不知道是否存在这种执行顺序问题？

**Comment by 2881099** [comment]
目的只发现这一个容易掉坑的问题，如果能解决就完美了。

示例已收录进文档：https://freesql.net/guide/unitofwork-manager.html

**Comment by inversionhourglass** [comment]
`MoAttribute`的生命周期对应被织入方法的生命周期，对于你描述的这种情况，是符合预期设定的。当然你遇到的这种场景，可以通过`MethodContext.RealReturnType`判断返回值是否为`Task`，然后通过`ContinueWith`的方式在`Task`结束时执行`OnExit`逻辑。

以你文档中的`TransactionalAttribute`为例：
```csharp
[AttributeUsage(AttributeTargets.Method)]
public class TransactionalAttribute : Rougamo.MoAttribute
{
    // ...

    public override void OnExit(MethodContext context)
    {
        if (typeof(Task).IsAssignableFrom(context.RealReturnType))
        {
            ((Task)context.ReturnValue).ContinueWith(t => _OnExit());
        }
        else
        {
            _OnExit();
        }

        void _OnExit()
        {
            try
            {
                if (context.Exception == null) _uow.Commit();
                else _uow.Rollback();
            }
            finally
            {
                _uow.Dispose();
            }
        }
    }
}
```

补充说明一下，`MethodContext.RealReturnType`对于`Task/Task<T>`返回值但没有`async`语法的，其值就是`Task/Task<T>`本身，而如果使用了`async`语法，那么`Task`将对应`typeof(void)`，`Task<T>`将对应`typeof(T)`

**Comment by 2881099** [comment]
感谢，明白了。建议在首页特别说明一下

代码应该是 context.ReturnValue = ...

**Comment by 2881099** [comment]
感谢，明白了。建议在首页特别说明一下

代码应该是 context.ReturnValue = ...

**Comment by 2881099** [comment]
感谢，明白了。建议在首页特别说明一下

代码应该是 context.ReturnValue = ...

**Comment by inversionhourglass** [comment]
好的，我后续将这种情况记录到REAMDE中。

如果你希望替换返回值，请使用`context.ReplaceReturnValue(this, returnValue)`，直接通过`context.ReturnValue`设置返回值会跳过一些逻辑，这些逻辑在不同版本可能还会不一样。

**Comment by inversionhourglass** [comment]
对了，还有一点，`context.ReplaceReturnValue(this, returnValue)`只能在`OnEntry`和`OnSuccess`中使用，`OnExit`中无法修改返回值

**Comment by 2881099** [comment]
这就矛盾了啊，因为上面你给的代码需要获取 context.ReturnValue，这个在 OnEntry 获取不到吧。

**Comment by inversionhourglass** [comment]
在`OnExit`中可以获取返回值，但是不能修改。

在`OnEntry`中应该叫设置返回值，应用场景比如异常参数检查返回固定返回值和缓存直接返回。

**Comment by 2881099** [comment]
好的，先解决 Task async，谢谢

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/wiki/DI-UnitOfWorkManager
谢谢，文档已更新，全面替换 castle.core

**Comment by inversionhourglass** [comment]
不客气，你们知名的开源项目愿意使用这样一个起步不久的项目，是我的荣幸，感谢使用

**Comment by 2881099** [comment]
本来只提供 UnitOfWorkManager 功能，就缺个动态代理。

之前一直没有推荐动态代理类库，他们比较喜欢 castle.core，整理出来的文档看起来太复杂 https://freesql.net/extra/aop-freesql-autofac.html

肉夹馍关注有一段时间了，今天试了一下太好用了，没有理由不推荐给大家。

**Comment by inversionhourglass** [comment]
刚发布了1.2.0版本，新增了`ExMoAttribute`，这个Attribute对有async语法和没有async语法的方法采用一致的生命周期，这个可能对你有用，`TransactionalAttribute`可以改成下面这样：
```csharp
[AttributeUsage(AttributeTargets.Method)]
public class TransactionalAttribute : Rougamo.ExMoAttribute
{
    // ...

    public override void ExOnExit(MethodContext context)
    {
        try
        {
            if (context.Exception == null) _uow.Commit();
            else _uow.Rollback();
        }
        finally
        {
            _uow.Dispose();
        }
    }
}
```
还有一点提醒一下，`OnExit/ExOnExit`中通过`MethodContext.Exception == null`来判断方法是否抛出异常并不完全准确，如果在`OnException/ExOnException`中通过`MethodContext.HandledException`方法处理掉异常，那么`OnExit/ExOnExit`中`MethodContext.Exception`就会返回null，如果希望在异常被处理的情况下依旧Rollback，可以将判断条件改为`if (context.Exception == null) && !context.ExceptionHandled)`

**Comment by 2881099** [comment]
谢谢提醒，上面够用了，非常好用

**Comment by inversionhourglass** [comment]
![Image](https://github.com/user-attachments/assets/3a502d40-b53a-4162-b10d-622d9cd6a819)

我本地无法复现这个问题，大佬你本地用的什么版本的 Rougamo，4.0.4 和 5.0.0 都没能复现

**Comment by 2881099** [comment]
[BootstrapBlazorApp.Server.zip](https://github.com/user-attachments/files/20774751/BootstrapBlazorApp.Server.zip)

这个压缩包本来是.rar

**Comment by inversionhourglass** [comment]
感谢反馈，问题复现了，我研究一下。不过大佬上面说的解决办法貌似才是问题所在，注释掉 Refersh 上面的 Attribute 就正常了

**Comment by inversionhourglass** [comment]
问题已经找到并修复了，我新建了一个 issue(#106) 来处理这个问题。现在发布了一个预发版本 5.0.1-preview-1750248426，周末将发布正式版，再次感谢反馈

**Comment by 2881099** [comment]
好快，感谢感谢
