### ISSUE TITLE
不支持属性或者字段拦截

### ISSUE THREAD

**Issue by hzy-6** [inversionhourglass/Rougamo#17]
![image](https://user-images.githubusercontent.com/14025507/185920480-2201a5ad-bd13-4ac4-9b22-254161e06715.png)

**Comment by inversionhourglass** [comment]
字段是无法支持的，属性现在是已经支持的
```csharp
public string Name
{
    [Logging]
    get;
    [Logging]
    set;
}
```

另外这个库 [PropertyChanged](https://github.com/Fody/PropertyChanged) 可能有你需要的

**Comment by HaoZhiYing** [comment]
我需要做属性注入的方式，这样写太复杂了

**Comment by inversionhourglass** [comment]
只是对get set分别应用一次`Attribute`，并没有多复杂，你这个需求对实际编码效率提升并不是很大，但实现功能需要改动的代码并不少，这个功能在空闲的时候可能会做，近期应该不会去实现这个

**Comment by HaoZhiYing** [comment]
好的，谢谢提供这么好的插件，期待完善。

**Comment by victor596** [comment]
会支持类似cache之类的操作吗？ 即在OnEntry阶段就熔断后续的操作

**Comment by inversionhourglass** [comment]
@victor596 已经支持了，你可以看这个issue里的回答，https://github.com/inversionhourglass/Rougamo/issues/12

如果你还有其他疑问可以新建一个issue，两个不相关的问题不适合在同一个issue中提出

**Comment by sgf** [comment]
库是好库，可惜多数人不识货，不会用。 .net开发人员的素质普遍不算高。

**Comment by inversionhourglass** [comment]
@taylortaurus 异常方法里的字段？不明白你的需求，这个和当前issue相关吗？不相关的话，请新开一个issue

**Comment by inversionhourglass** [comment]
已发布2.0
