### ISSUE TITLE
OnEntry.ReplaceReturnValue拦截出现问题

### ISSUE THREAD

**Issue by victor596** [inversionhourglass/Rougamo#18]
OnEntry.ReplaceReturnValue拦截对不带async关键字的 Task<T>,ValueTask<T> 方法时不能正确处理

**Comment by inversionhourglass** [comment]
这个不算不能正确处理，可以参考我在 #14 里的说明，你可以通过`MethodContext.RealReturnType`判断返回值是否是`Task/Task<T>`来区别的设置返回值，也可以通过`MethodContext.IsAsync`判断当前方法是否使用了`async`语法来区别设置返回值。

这个设定基本不会变，不过在 #14 提出后我在考虑进行扩展来简化这种情况下需要写的逻辑代码，这个会需要一些时间，暂时需要你们自己实现这些逻辑处理

**Comment by victor596** [comment]
按照你给的建议确实可以

**Comment by inversionhourglass** [comment]
刚发布了1.2.0版本，新增了`ExMoAttribute`，这个Attribute对使用和没使用async语法的方法保持一致的处理方式，你可以更新到1.2.0版本试试，`ExMoAttribute`的方法名与`MoAttribute`稍有不同，`OnEntry/OnException/OnSuccess/OnExit`对应改为`ExOnEntry/ExOnException/ExOnSuccess/ExOnExit`。其他信息可以从 [readme](https://github.com/inversionhourglass/Rougamo#%E5%AF%B9asyncnon-async%E6%96%B9%E6%B3%95%E7%BB%9F%E4%B8%80%E5%A4%84%E7%90%86%E9%80%BB%E8%BE%91v120)里了解
