### ISSUE TITLE
未能加载文件或程序集“System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”或它的某一个依赖项。系统找不到指定的文件

### ISSUE THREAD

**Issue by flysafely** [inversionhourglass/Rougamo#21]
![image](https://user-images.githubusercontent.com/2851364/203771198-eeb3b61f-0b2f-43e7-9b34-d1bc40212fb3.png)
大佬，想要捕获异常后修改返回值，结果提示dll没加载...

**Comment by inversionhourglass** [comment]
你项目framework版本多少，再贴一下你这个异常的调用堆栈

**Comment by flysafely** [comment]
Framework  v4.8

**Comment by flysafely** [comment]
Rougamo 1.2.0

**Comment by flysafely** [comment]
![image](https://user-images.githubusercontent.com/2851364/203978888-02ab6ed0-d917-4d19-ac75-86bebbdfc111.png)
就是在这个里面抛出的异常，而且我发现反编译出来的代码跟github上您贴出来的代码不太一样...
ps：
另外还会存在一个问题，就是在调用写好的Attribute特性在我想要织入的函数，必须在代码入口靠前的一个函数上也设置这个特性，才能保证后面调用的地方能够成功的进入OnEntry等函数，否则不能正常执行...

**Comment by inversionhourglass** [comment]
你一开始的异常和后面说的这个情况，我都没有复现出来。你使用Rougamo封装的类所在的项目是发布成nuget后你实际应用再通过nuget引用，还是在同一个解决方案直接通过项目引用的？

另外你看你应用Attribute的方法所在的项目是否引用了Rougamo这个nuget以及在编译时是否在项目根目录生成了`FodyWeavers.xml`文件。

如果你前面说的这些情况发生的很普遍，你看能否新建一个简单的测试项目复现这个问题，然后提交到github，我这边拉取代码后更方便解决

**Comment by flysafely** [comment]
我是在项目中通过Nuget安装您的Rougamo，然后引用，通过最简单的代码在一个添加了集成自MoAttribute的特性描述函数中throw一个Exception，预期是能够进入到OnException方法中，的确也进入了，通过您在Readme文件描述的，可以通过context.HandledExceptionhu方法表明异常已处理并设置返回值, 正如我第一次提交给您的那张图的那个函数，就出现了dll未加载的异常。
我本想直接拉取源码，在本地编译您的代码，后在我程序中调用，但是我发现，编译后，并不能在我的项目根目录下生成FodyWeavers.xml文件或者有文件但是里面没有<Rougamo/> 节点，不知道是不是还有什么地方需要进行配置的...
我对C#项目不太熟悉，我现在主要是用C#进行Revit二次开发，我的代码其实编译成dll后，被Revit进行调用的...可能您那边不太好复现...

**Comment by flysafely** [comment]
如果您方便的话，我可以跟你约个时间，或者您留下一个方便的联系方式，您远程debug一下，我觉得按照您的水平，这个问题并不困难，但是对于我来说，可能就只能止步于此了...非常感谢大佬！

**Comment by flysafely** [comment]
我的微信号：Mofioso
