### ISSUE TITLE
看文档加了一个ExMoAttribute ，那么基于接口的是可以天然支持异步么？

### ISSUE THREAD

**Issue by sgf** [inversionhourglass/Rougamo#22]
看文档加了一个ExMoAttribute ，那么基于接口的是可以天然支持异步么？

**Comment by inversionhourglass** [comment]
没太明白你的问题，ExMoAttribute是用来解决在没有使用async/await语法时，也可以像使用了async/await语法那样直接操作Task/ValueTask执行完成的返回值，而不是Task/ValueTask本身。可以参考v1.2.0版本说明里的例子 https://github.com/inversionhourglass/Rougamo/releases/tag/v1.2.0

**Comment by sgf** [comment]
```C#
[General]
[Ex]
public Task<int> M()
{
    return Task.FromResult(0);
}



// 1.定义需要织入的代码，也可以直接使用快速开始中定义的LoggingAttribute
public class LoggingMo : IMo
{
    public  AccessFlags Flags => AccessFlags.All;

    public void OnSuccess(MethodContext context)
    {
        Log.Info("方法执行成功后");

        **// 这里是否可以这么做?**
        context.ReplaceReturnValue(this, 2);

    }
}
```

**Comment by inversionhourglass** [comment]
IMo不行，必须继自ExMoAttribute，然后在ExOnSuccess方法在执行替换返回值的操作，因为对于没有async/await语法的方法，Task的处理逻辑是在ExMoAttribute里实现的

**Comment by sgf** [comment]
> 

那接口这块 async/await 就不好弄了, 不行的话就手写下 Task.FromResult 吧,未必用得着, 估计主要就是记录个日志,一般用不上修改返回值 ┑(￣Д ￣)┍

**Comment by inversionhourglass** [comment]
非必要不要直接实现IMo接口，MoAttribute和ExMoAttribute都实现了IMo接口，直接继承这两个类就好了

**Comment by inversionhourglass** [comment]
应该是我README里的例子给你造成了误解，README里空接口的那个功能主要说的是IRougamo这个接口，LoggingMo不是必须直接实现IMo，可以直接继承MoAttribute或ExMoAttribute。这个文档我晚点改一下
