### ISSUE TITLE
rougamo 具体怎么用的?

### ISSUE THREAD

**Issue by sgf** [inversionhourglass/Rougamo#23]
我按照readme的例子写了一下.然后程序启动后就没有然后了.

```C#

public interface IJobHub : IRougamo<JobLoopLogging>
{
    /// <summary> 任务集合标题 </summary>
    public string Title { get; }

    /// <summary> 任务集合描述 </summary>
    public string Description { get; }
}


// 1.定义需要织入的代码，也可以直接使用快速开始中定义的LoggingAttribute
public class JobLoopLogging : ExMoAttribute
{

}
```

然后我定义了各种类型 实现了 IJobHub 接口.然后呢?

是不是需要什么触发机制?
我这边在JobLoopLogging 中的 ExOnEntry 下了断点,没有触发

JobLoopLogging的构造函数甚至都没有构造.

环境:  win10 x64,   .net 6 ,   winform 程序

**Comment by inversionhourglass** [comment]
你定义的各种实现了`IJobHub`的类型的方法（非构造方法和属性方法）在被访问时会执行`JobLoopLogging.ExOnEntry`，你如果实在是无法执行到`ExOnEntry`中，你可以在github上建一个测试项目，然后把地址发我，我clone下来看你的问题

**Comment by sgf** [comment]
> 你定义的各种实现了`IJobHub`的类型的方法（非构造方法和属性方法）在被访问时会执行`JobLoopLogging.ExOnEntry`，你如果实在是无法执行到`ExOnEntry`中，你可以在github上建一个测试项目，然后把地址发我，我clone下来看你的问题

有qq群吗? 项目构造demo怕要耗费不少时间.可以进群发向日葵给你.

**Comment by inversionhourglass** [comment]
没有QQ群，看你的问题是最基本的功能都无法使用，新建一个很简易的demo项目即可，先通过demo项目了解如何使用，之后再应用到项目中。

你后面说的那个建议是不错的，我之前也考虑过做这方面的扩展，还考虑过用java的aspectj的那种形式，不过还是因为有其他工作以及懒最终到现在都还没有开始，可能还要再拖一阵子，再等等吧

**Comment by sgf** [comment]
> 没有QQ群，看你的问题是最基本的功能都无法使用，新建一个很简易的demo项目即可，先通过demo项目了解如何使用，之后再应用到项目中。
> 
> 你后面说的那个建议是不错的，我之前也考虑过做这方面的扩展，还考虑过用java的aspectj的那种形式，不过还是因为有其他工作以及懒最终到现在都还没有开始，可能还要再拖一阵子，再等等吧

我自己的计划任务的JobLoopAttribute继承了 ExMoAttribute,然后在方法上打标签 也不行,我猜测不知道是不是因为我的计划任务方法都是自己通过反射调用导致的.

不过按理 ruogamo属于静态编织.emm...
我试试放在 普通的Service上面看看.

**Comment by sgf** [comment]
> 没有QQ群，看你的问题是最基本的功能都无法使用，新建一个很简易的demo项目即可，先通过demo项目了解如何使用，之后再应用到项目中。
> 
> 你后面说的那个建议是不错的，我之前也考虑过做这方面的扩展，还考虑过用java的aspectj的那种形式，不过还是因为有其他工作以及懒最终到现在都还没有开始，可能还要再拖一阵子，再等等吧

经过测试,一点反应也没有.
然后...请看下一贴.

**Comment by sgf** [comment]
> 你后面说的那个建议是不错的，我之前也考虑过做这方面的扩展，还考虑过用java的aspectj的那种形式，不过还是因为有其他工作以及懒最终到现在都还没有开始，可能还要再拖一阵子，再等等吧

还发现一个问题. Fody是不是不能够区分 属性和方法.

老是拦截属性的 Get方法.  看来,只能够通过打标签的方式用 rougamo了😂
