### ISSUE TITLE
当方法参数未被使用时可能会有问题

### ISSUE THREAD

**Issue by tiansfather** [inversionhourglass/Rougamo#29]
我有一类库引用了Rougamo.Fody,在其中使用接口方式进行拦截，其中某一个类中有如下方法
![image](https://user-images.githubusercontent.com/16606743/207779869-78e9e891-960c-4b31-8df0-a6e2e59fa902.png)

此时发布nuget包会报以下错误：
![image](https://user-images.githubusercontent.com/16606743/207779244-6efc4d9c-a986-4e45-903c-8facbad3c219.png)

可能是由于参数没有被使用，所以优化掉了
当调整为如下形式
![image](https://user-images.githubusercontent.com/16606743/207780039-dad37035-28cc-423b-8f5e-39c967341b62.png)
![image](https://user-images.githubusercontent.com/16606743/207780071-2eca3c59-66c9-434f-984e-258c1e863000.png)

则没有问题

**Comment by inversionhourglass** [comment]
反馈收到，暂时避免代码出现这种情况吧，目前有些忙，需要晚些时候才能修复

**Comment by inversionhourglass** [comment]
已发布1.3.1版本
