### ISSUE TITLE
在切面不同时点间传递信息

### ISSUE THREAD

**Issue by dboydboy** [inversionhourglass/Rougamo#3]
是否可以实现在切面不同时点（方法）间传递数据？
例如，在OnEntry方法中获取了一些额外的信息，希望在OnSuccess时可以使用这些信息...
之前使用AspectCore，它的AspectContext中有一个名为AdditionalData的Dictionary，允许用户可以向其中添加数据...

**Comment by inversionhourglass** [comment]
你可以在你实现`MoAttribute`的类上定义字段，`OnEntry`的时候赋值，`OnSuccess`取值使用，`MoAttribute`是每次切面的时候都会创建一个实例，不存在并发问题

**Comment by dboydboy** [comment]
了解！
