### ISSUE TITLE
异步方法无法编译通过

### ISSUE THREAD

**Issue by 2876** [inversionhourglass/Rougamo#30]
``` internal class Program
    {
        static void Main(string[] args)
        {

        }


        [ExceptionHandle]
        private static async Task Test(string arg1)
        {

        }
    }


    [AttributeUsage(AttributeTargets.Method)]
    public sealed class ExceptionHandleAttribute : MoAttribute
    {
        public override void OnException(MethodContext args)
        {
            args.HandledException(this, "");
        }
    } ```

**Comment by 2876** [comment]
![微信图片_20221219161025](https://user-images.githubusercontent.com/51232529/208378283-d61bef8b-fd03-4269-a1d3-84121040bd86.png)

**Comment by inversionhourglass** [comment]
你这个和 #29 是同一个问题，方法定义了参数但是没有使用时才会出现的报错，这个是1.3.0版本新增功能里的bug，暂时有两个解决方案：
1. 避免方法定义了参数但是不使用的情况；
2. 降级至1.2.1

同一个BUG只打开一个issue，这个issue就先关闭了，这个BUG相关的后续更新将在 #29 中同步，你可以订阅那个issue来获取通知

Duplicate of #29

**Comment by 2876** [comment]
这个似乎不是同一问题。使用了参数，一样会有这个错误
![微信图片_20221219161025](https://user-images.githubusercontent.com/51232529/208557386-9f0c703c-62f3-4123-b3cc-78fcae42bcd0.png)

**Comment by inversionhourglass** [comment]
确实不是同一个问题，这个issue我重新打开，目前建议降级至1.2.1

**Comment by inversionhourglass** [comment]
已发布1.3.1版本
