### ISSUE TITLE
VS2019版本MSBuild编译存在System.ValueTuple未能加载的问题

### ISSUE THREAD

**Issue by flysafely** [inversionhourglass/Rougamo#31]
![6d56eab99f1e9ad8c591dc39d72123a](https://user-images.githubusercontent.com/2851364/209494794-bfc185e2-c410-4361-9872-02a848d2f575.jpg)
目前有两种解决方法：
1.将VS版本升级到2021或者更高(可能是编译器升级后将引用重定向，问题解决)
2.将Rougamo版本降低到1.1.4-alpha版本(作者在改版本中取消了使用ValueTuple，问题解决)

**Comment by inversionhourglass** [comment]
根据错误中的相关 [issue](https://github.com/dotnet/runtime/issues/27533) 可知，该问题主要在于老的NuGet管理方式会自动在 app.config 中添加 `dependentAssembly` 节点，从而导致 `System.ValueTuple.dll` 没有在编译时输出到bin目录中。
在相关 [issue](https://github.com/dotnet/runtime/issues/27533) 中给出的主要解决方式是将NuGet管理方式升级为 `PackageReference` ，关于如何升级可以参考 [官方文档](https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference) 。
在相关 [issue](https://github.com/dotnet/runtime/issues/27533) 中的另一个解决方案是将 `System.ValueTuple.dll` 手动拷贝到 GAC 目录
> C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.ValueTuple\v4.0_0.0.0.0__cc7b13ffcd2ddd51
@flysafely 提到的第一种解决方案，可能是高版本的VS会执行这一步，也可能是高版本的VS在老的NuGet管理方式上与低版本的有所不同。
Rougamo为了避免这个问题，将修改代码中使用到`ValueTuple`的地方， @flysafely 提到的`1.1.4-alpha`版本是针对于他所面临的其他问题所特用的版本。考虑到这个问题是相对限定的场景才会发生，所以不会针对该问题发布一个新的NuGet版本，该问题将在下一个正式版中一同修复。

**Comment by inversionhourglass** [comment]
该问题已在1.3.4版本中一同修复
