### ISSUE TITLE
NullReferenceException when intercepting a method which return List<T>

### ISSUE THREAD

**Issue by murrays1208049** [inversionhourglass/Rougamo#35]
My code like the following:

![image](https://user-images.githubusercontent.com/4969802/219531047-50969fdb-08f2-460d-b71e-e4a003d5495b.png)

At the very beginning, the exception is the **same** with which in issue#27 [https://github.com/inversionhourglass/Rougamo/issues/27](url).
Then,I upgrade to **1.3.3**.

But now, exception still there with the following stack:

System.NullReferenceException: Object reference not set to an instance of an object.

> at Rougamo.ExMoAttribute.TryResolve(Type type, Object returnValue, Func`3& func)
> at Rougamo.ExMoAttribute.OnSuccess(MethodContext context)
> ....

The **difference** of my new issue and the issue#27 is :
```
my issue: Rougamo.ExMoAttribute.TryResolve(Type type, Object returnValue, Func`3& func)
issue#27: Rougamo.ExMoAttribute.TryResolve(Type type, Func`3& func)
```

**Comment by inversionhourglass** [comment]
Thanks for your feedback, it will be fix later.

**Comment by inversionhourglass** [comment]
1.3.4 has been released, you can update and try again.

**Comment by murrays1208049** [comment]
so rapid reply!
