### ISSUE TITLE
调试时无法步入添加了切面的方法

### ISSUE THREAD

**Issue by TianCaibailei** [inversionhourglass/Rougamo#36]
如题，只能看到反汇编代码

**Comment by inversionhourglass** [comment]
感谢反馈，这个是已知问题，预计会在2.0.0版本修复，目前的建议是在需要调试的方法上添加断点，然后直接运行到断点处，或者继续步入几次后进入实际方法

**Comment by inversionhourglass** [comment]
这个问题在2.0版本无法进行修复。这是由于肉夹馍采用的是最小代码织入，直接在目标方法织入代码，如果需要支持较好的调试体验，需要采取另一种织入方式，这种方式在同步方法上产生的额外织入代码还好，但是在异步方法上将产生大量的额外织入代码。

后续可以考虑通过配置或者判断debug模式以方便调试的方式织入代码，release模式以最小织入的方式织入代码。这个改动会比较多，将不在2.0版本提供，后续再看情况。

**Comment by hzy-6** [comment]
这个问题希望能尽快安排上，基本就稳定可靠了

**Comment by bxjg1987** [comment]
请问下大佬，这个问题有进展吗？

**Comment by inversionhourglass** [comment]
> 请问下大佬，这个问题有进展吗？

正在开发中，近期还有些别的事，所以还需要些时间

**Comment by inversionhourglass** [comment]
3.0版本已发布，支持步入调试
