### ISSUE TITLE
字段值如何获取

### ISSUE THREAD

**Issue by taylortaurus** [inversionhourglass/Rougamo#38]
请问，在postsharp中字段值可以这样获取，在肉夹馍中如何获取，菜狗的提问。
```
public override void OnEntry(MethodExecutionArgs args)
{
    Report.Info("[AOP]Entry Method=" + args.Method.Name);

    testInfo.TestCaseId = Convert.ToString(args.Method.ReflectedType.GetField("testCaseId").GetValue(args.Instance));
}
```
@inversionhourglass

**Comment by inversionhourglass** [comment]
感觉你没有尝试过，`MethodContext`有类似的属性值，`MethodContext.Method`可以过去当前织入方法，`MethodContext.TargetType`可以获取织入方法所属的类型，`MethodContext.Target`可以获取当前实例。那么获取字段值的方式就跟你上面的实现类似了

**Comment by taylortaurus** [comment]
> 感觉你没有尝试过，`MethodContext`有类似的属性值，`MethodContext.Method`可以过去当前织入方法，`MethodContext.TargetType`可以获取织入方法所属的类型，`MethodContext.Target`可以获取当前实例。那么获取字段值的方式就跟你上面的实现类似了

尝试了，没成功，可能没写对吧，我刚试试，可以了，离了大普，菜狗的懵逼
