### ISSUE TITLE
关于Flags赋值的问题

### ISSUE THREAD

**Issue by Harper0712** [inversionhourglass/Rougamo#40]
目前无法支持用attribute的参数来为Flags赋值，有一种场景是整个应用程序使用同一个LoggingAttribute，对于不用的class想实现不用的method level

**Comment by inversionhourglass** [comment]
> 目前无法支持用attribute的参数来为Flags赋值

你说的是指这种吗：`[Logging(Flags = AccessFlags.Public)]`，这种应该是支持的，你试着不行吗。

**Comment by Harper0712** [comment]
对的，就是想达到这种效果，试过了，不行的。我大概看了一下Rougamo.Fody的代码，它是加载编译后的dll，反射获取MoAttribute派生类中的Flags，而构造函数是在运行时才赋值的，所以这么做不会起作用的。得改Rougamo.Fody才行。

**Comment by inversionhourglass** [comment]
你看代码的理解不太对，或者说你的描述不对。rougamo没有使用到你说的反射获取Flags属性值，继承`MoAttribute`重写`Flags`属性的值是通过解析IL获取的。另外Attribute的构造参数值不是运行时才赋值的，Attribute的构造参数值是直接写入到IL中，这个你可以通过反编译dll看到。

你说的这个问题我看了下，功能上是可以实现的，不过现在确实存在一个类型转换bug导致无法获取到这个值，这个将在后续版本中修复，感谢反馈。

**Comment by inversionhourglass** [comment]
2.0版本将提供表达式匹配方法的方式，这个对你这种批量应用的场景获取更适用，后续可以关注一下

**Comment by Harper0712** [comment]
谢谢指正，期待2.0版本

**Comment by inversionhourglass** [comment]
已发布2.0
