### ISSUE TITLE
想获取方法内执行的参数再传入Rougamo

### ISSUE THREAD

**Issue by loveyeguo** [inversionhourglass/Rougamo#49]
我有一个需求，记录日志详情，方法内执行一个方法 
 var x=CreateOrder();
我需要获取这个x并传入Rougamo，然后Rougamo内部的OnSuccess方法写
WriteLog(x)；
我应该如何传入这个x呢？

**Comment by loveyeguo** [comment]
伪代码大概是
[这里为特性注入]
void XXXMethod()
{
       var x=CreateOrder();
}

**Comment by inversionhourglass** [comment]
这个目前无法直接取到，只能取方法参数、当前对象的属性以及全局变量。
方法内部如果有数据需要与肉夹馍交互，一般推荐通过一个中间层进行对接，比如暴力点直接使用`ThreadLocal`或者`AsyncLocal`传递数据，或者委婉点定义一个数据传递中间件，用肉夹馍实现一个接受/读取端，这样也方便万一后续换其他AOP组件，可以直接切换实现。可以参考 #43 的回复。

**Comment by loveyeguo** [comment]
我想想，一下没看明白，我没使用过AsyncLocal

**Comment by loveyeguo** [comment]
如果每个函数内部都要使用一个AsyncLocal，那好像侵入性太大了。或者我是否可以获取某个函数的返回值，把返回值作为入参传入Rougamo,只是这样局限性很大。多个入参就不适用了。

**Comment by inversionhourglass** [comment]
你说的某个方法的返回值是指类似你上面伪代码中`CreateOrder`的返回值吧，这种获取不到的，只能获取当前方法自身的返回值，也就是伪代码中`XXXMethod`的返回值

想要在肉夹馍中过去被织入方法内部代码变量是不可行的，存在变量作用域的问题

**Comment by loveyeguo** [comment]
嗯，理解，感谢大佬。
其实我在项目中实际遇到的问题是，我有很多种操作记录表，工单表，任务表，发货表等等。同时我有一个通用的日志表，我需要把这三种表的操作步骤，统一记录到日志表中，所以我需要在新增记录表，工单表，任务表的方法中，获取到插入数据的ID，然后新增一条日志表，同时吧这个插入数据ID关联起来。如果能在每个新增方法中加入AOP，统一记录，就比较好。
但是我现在无法获取这个插入ID。。。
我应该怎么实现比较好？

**Comment by loveyeguo** [comment]
`或者委婉点定义一个数据传递中间件，用肉夹馍实现一个接受/读取端，这样也方便万一后续换其他AOP组件，可以直接切换实现`

这个，源码demo里面能给一个简单的示例么，确实没有很好的理解。但是感觉这个需求是比较通用的

**Comment by inversionhourglass** [comment]
根据你前面描述的，大概是下面这样的代码：
```csharp
[Logging]
public void M()
{
    var x = M1();
    var y = M2();
    var z = M3();
}
```
你现在是需要获取到x,y,z然后关联起来记日志？分开记录是一定不行的吗，如果可以分开记录，分别在M1,M2,M3上增加Attribute就可以了

**Comment by loveyeguo** [comment]
好像不是我想要表达的，我再详细说一下哈。
我有一个方法 CreateOrder，用来新增订单，同时我有一个全局的日志方法，这个方法入参里面有个OrderID，是CreateOrder函数中生成的，伪代码大概如下：

`
[CommonLog]
public void CreateOrder()
{
   //新增订单记录
     var OrderID=Add();
}

public class CommonLogAttribute : MoAttribute
{
   //我想在这里能够获取到OrderID，然后插入日志
   AddLog(OrderID);
}
`
我如何在函数中，把CommonLogAttribute需要的参数OrderID传入进去呢？

**Comment by loveyeguo** [comment]
我最后想实现的效果，就是项目中有N个方法，我都可以统一标记上 [CommonLog] ，然后传递一个OrderID进去，日志就会自动帮我记录。

**Comment by loveyeguo** [comment]
我仔细看了另外一个组件“PostSharp”，好像也没有类似这样的操作，只能获取函数的入参，返回值等等信息。
可能我这个需求根本不适宜用AOP处理？

**Comment by inversionhourglass** [comment]
你没看明白我的例子，如果你只是想在`Add`后将`OrderID`记录到日志中，你只需要在你的`Add`方法上应用`CommonLogAttribute`即可。你不应该想着怎么在AOP中获取方法内部的变量数据，前面也说了，变量是存在作用域问题的。标准的AOP能够操作的就是入参和返回值，如果就是想要AOP与方法内部数据交互，就是需要中间载体，参考 #43

**Comment by loveyeguo** [comment]
明白了，然后Add方法的返回值设置为OrderID。 谢谢大佬！
