### ISSUE TITLE
派生自MoAttribute的特性的Inherited失效

### ISSUE THREAD

**Issue by ViewSuSu** [inversionhourglass/Rougamo#56]
[AttributeUsage(AttributeTargets.Class, Inherited = true)]
    public class LogAttribute : MoAttribute
    
    请教一下作者，继承自MoAttribute的特性是不是没办法应用于派生类？
    
    我的需求是：希望这个特性标记一个抽象基类，然后派生自这个抽象类的子类都携带MoAttribute里的方法和属性，但是好像失效了

**Comment by inversionhourglass** [comment]
对的，这种方式无法生效，不过可以通过实现空接口`IRougamo<LogAttribute>`来实现你的需求

**Comment by ViewSuSu** [comment]
感谢作者解答！您的框架完美地解决了我的业务需求！

**Comment by inversionhourglass** [comment]
感谢使用和支持
