### ISSUE TITLE
如何获取泛型类型的 真实泛型参数 T

### ISSUE THREAD

**Issue by hzy-6** [inversionhourglass/Rougamo#58]
![image](https://github.com/inversionhourglass/Rougamo/assets/14025507/bae3dce1-7fe6-4976-b12e-18856965c8a0)
![image](https://github.com/inversionhourglass/Rougamo/assets/14025507/10342779-983f-4a15-bae8-b49c0f7615fa)
![image](https://github.com/inversionhourglass/Rougamo/assets/14025507/4edf3162-e8d3-441b-9149-9742a57fc4c9)

**Comment by hzy-6** [comment]
通过 目标类型 找属性可以获得真实类型 
![image](https://github.com/inversionhourglass/Rougamo/assets/14025507/8906c9d4-7d90-4fbf-aebb-673d229712c9)

**Comment by inversionhourglass** [comment]
你的这个例子中，可以直接通过Target的类型获取泛型参数
```csharp
context.Target.GetType().GetGenericArguments()
```

**Comment by hzy-6** [comment]
好的明白了，目前是就这样通过 Target 属性来取的
