### ISSUE TITLE
使用 Rougamo 2.2.0 源码无法AOP,

### ISSUE THREAD

**Issue by abramped** [inversionhourglass/Rougamo#59]
无论是直接依赖工程还是发布nupkg，都无法AOP成功。
官方发布版本就可以AOP成功。

**Comment by inversionhourglass** [comment]
> 无论是直接依赖工程还是发布nupkg，都无法AOP成功。

你是指你自己编译发布的Rougamo吗

**Comment by abramped** [comment]
> > 无论是直接依赖工程还是发布nupkg，都无法AOP成功。
> 
> 你是指你自己编译发布的Rougamo吗
> 
> > 官方发布版本就可以AOP成功。
> 
> 官方发布版本又是指什么，Rougamo的官方版本吗
自己编译发布的Rougamo版本AOP失败，无任何修改。Rougamo的官方版本AOP成功。

**Comment by inversionhourglass** [comment]
在解决方案根目录执行以下命令，执行成功后nuget会生成到根目录下的nugets目录
```
dotnet pack Rougamo.sln --configuration Release
```

**Comment by abramped** [comment]
感谢回复！
