### ISSUE TITLE
请问如何阻止异常的继续抛出？

### ISSUE THREAD

**Issue by SeptSky** [inversionhourglass/Rougamo#6]
我通过反汇编查看织入的代码大致结构如下：
// 创建切面的实例
try
{
// 嵌入的方法代码
}
catch(Exception exception)
{
  methodContext.Exception = exception;
  ((IMo)methodExceptionAttribute).OnException(methodContext);
  throw; // 此处能否控制不继续抛出异常？这种方式与Reactive.UI异步代码不好配合处理异常逻辑
}
谢谢！

**Comment by inversionhourglass** [comment]
`rougamo`当前的版本主要提供日志和APM的埋点支持，暂时不支持异常处理和返回值修改，近期会考虑完成这些功能，可以持续关注一下

**Comment by inversionhourglass** [comment]
@SeptSky 我发布了1.1.0-alpha版本，你可以先用的看看，使用方法参考我 [更新的文档](https://github.com/inversionhourglass/Rougamo#%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E5%92%8C%E4%BF%AE%E6%94%B9%E8%BF%94%E5%9B%9E%E5%80%BCv110)，正式版还需要一段时间

**Comment by SeptSky** [comment]
@inversionhourglass 多谢！
