### ISSUE TITLE
返回值是Tuple的怎么快速获取到具体的返回值？

### ISSUE THREAD

**Issue by LemonDXR** [inversionhourglass/Rougamo#62]
方法如下： public async Task<(bool, UserInfo, string)> Index(UserQuery query){}。。目前我在退出的方法中获取到的returnValue的值如下：(true, {WebApplication5.Models.UserInfo}, "")，有没有什么方法可以方便解析返回值

**Comment by inversionhourglass** [comment]
`MethodContext.ReturnValue`保存了方法返回值，你知道返回值类型，直接类型强转就可以了
