### ISSUE TITLE
能不能在OnEntry，根據某些條件，中斷實際方法的執行  類型與執行 next() 才會執行真正方法

### ISSUE THREAD

**Issue by yundexiaobin** [inversionhourglass/Rougamo#67]
能不能在OnEntry，根據某些條件，中斷實際方法的執行  類似與執行 ActionFilter  調用 next() 才會執行真正方法

**Comment by inversionhourglass** [comment]
可以通过`MethodContext`的`ReplaceReturnValue`方法设置返回值跳过实际方法执行，可以参考 [修改返回值](https://github.com/inversionhourglass/Rougamo?tab=readme-ov-file#%E4%BF%AE%E6%94%B9%E8%BF%94%E5%9B%9E%E5%80%BC)
