### ISSUE TITLE
async void方法织入方式投票及讨论

### ISSUE THREAD

**Issue by inversionhourglass** [inversionhourglass/Rougamo#68]
由于3.0版本中使用代理调用的方式进行代码织入，这种方式会导致async void方法织入的代码无法确保在实际方法执行完毕后执行`OnExit`系列方法，下面是3.0版本前后对于async void方法织入代码后的简单代码对比示例：
```csharp
// 原始方法
public async void MAsync()
{
    Console.WriteLine(1);
    await Task.Delay(2000);
    Console.WriteLine(2);
}

// 3.0版本之前代码织入后简单示例
public async void MAsync()
{
    var context = new MethodContext(...);
    var mo = new TestMoAttribute();
    mo.OnEntry(context);
    try
    {
        Console.WriteLine(1);
        await Task.Delay(2000);
        Console.WriteLine(2);

        mo.OnSuccess(context);
    }
    catch (Exception e)
    {
        context.Exception = e;
        mo.OnException(context);
    }
    finally
    {
        mo.OnExit(context);
    }
}

// 3.0版本之后将原方法拷贝为$Rougamo_MAsync
public async void $Rougamo_MAsync()
{
    Console.WriteLine(1);
    await Task.Delay(2000);
    Console.WriteLine(2);
}

// 然后修改原方法进行代码织入
public void MAsync()
{
    var context = new MethodContext(...);
    var mo = new TestMoAttribute();
    mo.OnEntry(context);
    try
    {
        MAsync();

        mo.OnSuccess(context);
    }
    catch (Exception e)
    {
        context.Exception = e;
        mo.OnException(context);
    }
    finally
    {
        mo.OnExit(context);
    }
}
```

正如上面的代码所示，在3.0版本之后，在执行`OnSuccess`和`OnExit`时，`$Rougamo_MAsync`可能还处于`Task.Delay(2000)`的状态，实际并没有执行完毕，并且，如果`$Rougamo_MAsync`在`await Task.Delay(2000)`之后发生了异常，该异常也是无法在`MAsync`中被捕获的。

考虑到winform和wpf可能存在较多async void的使用方式，这样的改动可能无法满足当前的使用要求。所以在当前issue中发起一个投票，是否需要将async void的代码织入方式保持为3.0版本之前的方式，或者目前winform/wpf对于async void的写法已经有更好的替代方式，可以支持3.0版本中代理调用的织入方式。

**需要额外说明的是，3.0版本支持了方法的步入调试，但如果采用3.0版本之前的织入方式，那么async void方法将不支持步入调试**

我在下面会回复几种投票选项，如果你任何其中某种方式，请点赞对应评论，如果有其他建议也可以评论回复，同样可以作为投票选项。该投票将持续到4.0版本开发末期，issue关闭后将不再统计。

**Comment by inversionhourglass** [comment]
使用3.0版本的代理调用织入方式

（winform / wpf 或其他使用async void的项目有较好方式规避async void用法时，默认代理调用的方式更佳）

**Comment by inversionhourglass** [comment]
使用3.0版本之前的内嵌织入方式

（无法很好规避async void用法，同时需要正确的`OnExit`方式执行时机）

**Comment by inversionhourglass** [comment]
默认使用3.0版本的代理调用织入方式，可通过配置修改织入方式

（配置的方式为修改`FodyWeavers.xml`文件中的配置）

**Comment by inversionhourglass** [comment]
默认使用3.0版本之前的内嵌织入方式，可通过配置修改织入方式

（配置的方式为修改`FodyWeavers.xml`文件中的配置）

**Comment by hzy-6** [comment]
async void 就不让这样用

**Comment by hzy-6** [comment]
最好还是测试一下 3.0 我用在生产环境跑不起来，似乎代理了函数后函数头部的特性没有生效

**Comment by inversionhourglass** [comment]
> 最好还是测试一下 3.0 我用在生产环境跑不起来，似乎代理了函数后函数头部的特性没有生效

有问题另开issue，另外附带有用信息，你就这么来一句，我怎么做

**Comment by inversionhourglass** [comment]
截止目前无任何投票，关闭此投票，后续自行决定处理方式，不再征集意见
