### ISSUE TITLE
blazor中使用3.0发布失败

### ISSUE THREAD

**Issue by bxjg1987** [inversionhourglass/Rougamo#69]
有个项目ZLJ.RCL是 RCL类库，它引用了肉夹馍3.0
然后建立blazor web app auto模式，在client项目中引用ZLJ.RCL

发布blazor的server项目时，提示：

严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误		优化程序集的大小失败。通过将 PublishTrimmed 属性设置为 false 可禁用优化。	ZLJ.Web.BlazorAuto		0		

严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误		IL Trimmer has encountered an unexpected error. Please report the issue at https://aka.ms/report-illink	ZLJ.Web.BlazorAuto	ILLink	0		

尝试在FolderProfile.pubxml中设置也无效：
<PropertyGroup>
  <PublishTrimmed>false</PublishTrimmed>
  <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
</PropertyGroup>

并且我发布时选择的依赖框架，没有选择独立部署，所以也没有勾选裁剪

不晓得为啥，我现在退回到2.3版本一切正常

**Comment by inversionhourglass** [comment]
blazor方面我不太了解，你能在github上建立一个简单的项目复现你说的这个情况吗，我拉倒本地看看

**Comment by bxjg1987** [comment]
很抱歉，应该是我vs出问题了，换台电脑就没事。抱歉哈！
