### ISSUE TITLE
根据说明文档建了测试环境，但不起作用

### ISSUE THREAD

**Issue by sicode** [inversionhourglass/Rougamo#70]
版本：3.0

是我哪里没引用？

以下是模拟环境，另外的项目也差不多
类项目直接引用肉夹馍 并基于MoAttribute扩展了自己的特性，在入口项目中引用且已经引用rougamo.fody
![image](https://github.com/inversionhourglass/Rougamo/assets/3986116/f3e97196-2126-4963-89b4-5d84207ebf08)

**Comment by inversionhourglass** [comment]
这个是要做什么，如果想使用肉夹馍，直接通过nuget引用，如果想调试源码，参考源码里的测试项目

**Comment by sicode** [comment]
> 这个是要做什么，如果想使用肉夹馍，直接通过nuget引用，如果想调试源码，参考源码里的测试项目

没事，我搞错了，fody 有版本要求 最低4.6.1，我建了一个4.5导致安装肉夹馍时候fody 装不上，最终没生效
