### ISSUE TITLE
使用结构体时 Feature 不起作用

### ISSUE THREAD

**Issue by DengWang** [inversionhourglass/Rougamo#72]
使用结构体时 Feature 不起作用, 即使只使用Feature.OnEntry 生成的il中还是会有其他的 Exception, Success, Exit

**Comment by inversionhourglass** [comment]
请提供具体代码，我测试是没问题的

**Comment by DengWang** [comment]
![image](https://github.com/inversionhourglass/Rougamo/assets/2217844/403d5d2f-2699-44f0-99f0-748a4f0af178)
这个代码用于检查方法是否在主线程调用

**Comment by inversionhourglass** [comment]
好的，感谢反馈，将尽快修复

**Comment by inversionhourglass** [comment]
问题已修复，已发布3.0.1

这个问题不是结构体的问题，是代码写法的问题，你截图中结构体属性的写法是`Features { get; } = Feature.OnEntry`，Attribute的写法是`Features => Feature.OnEntry`

我一开始测试没问题是因为我结构体属性的写法是后者，现在已经修复，两种写法都是支持的
