### ISSUE TITLE
3.0.0没有报错，3.0.1发布时报错了。

### ISSUE THREAD

**Issue by qcjxberin** [inversionhourglass/Rougamo#74]
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Failed to execute weaver F:\.nuget\packages\rougamo.fody\3.0.1\build\..\weaver\Rougamo.Fody.dll
1>MSBUILD : error : Type:
1>MSBUILD : error : System.Exception
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    在 InnerWeaver.ExecuteWeavers() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 222
1>MSBUILD : error :    在 InnerWeaver.Execute() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 113
1>MSBUILD : error : Source:
1>MSBUILD : error : FodyIsolated
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void ExecuteWeavers()
1>MSBUILD : error : 未将对象引用设置到对象的实例。
1>MSBUILD : error : Type:
1>MSBUILD : error : System.NullReferenceException
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    在 Rougamo.Fody.MonoExtension.HardClearCustomDebugInformation(MethodDefinition methodDef)
1>MSBUILD : error :    在 Rougamo.Fody.MonoExtension.Clear(MethodDefinition methodDef)
1>MSBUILD : error :    在 Rougamo.Fody.ModuleWeaver.ProxySyncMethodWeave(RouMethod rouMethod)
1>MSBUILD : error :    在 Rougamo.Fody.ModuleWeaver.SyncMethodWeave(RouMethod rouMethod)
1>MSBUILD : error :    在 Rougamo.Fody.ModuleWeaver.WeaveMos()
1>MSBUILD : error :    在 Rougamo.Fody.ModuleWeaver.Execute()
1>MSBUILD : error :    在 InnerWeaver.ExecuteWeavers() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 186
1>MSBUILD : error : Source:
1>MSBUILD : error : Rougamo.Fody
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void HardClearCustomDebugInformation(Mono.Cecil.MethodDefinition)
1>MSBUILD : error :

**Comment by inversionhourglass** [comment]
感谢反馈，这个错误信息很难确认具体什么样的方法产生的报错，如果你那边的报错信息能够定位到具体方法，把导致异常的方法的代码贴一下，方便复现问题

**Comment by inversionhourglass** [comment]
由于未补充有效信息，无法复现问题，仅通过为空判断规避该异常
