### ISSUE TITLE
织入代码后Swagger报错

### ISSUE THREAD

**Issue by aiken-hi** [inversionhourglass/Rougamo#75]

**Comment by aiken-hi** [comment]
![image](https://github.com/user-attachments/assets/6504b5c9-febf-409c-bbc5-a77190e46173)
![image](https://github.com/user-attachments/assets/4b5f88a8-5738-4086-b610-d224131a96f7)

**Comment by inversionhourglass** [comment]
感谢反馈，问题已修复，已发布3.1.0
