### ISSUE TITLE
Controller方法的属性问题

### ISSUE THREAD

**Issue by josephgugu** [inversionhourglass/Rougamo#76]
原方法属性是这样：
![image](https://github.com/user-attachments/assets/676e316f-98a4-46ba-a42e-8e9500c7ac82)
编织后的方法：
![image](https://github.com/user-attachments/assets/c9a87bdd-baab-40da-b1ea-49ed498b1971)
![image](https://github.com/user-attachments/assets/74452a72-f410-4d49-b551-c10e333c4b9e)
这样在请求进来之后，会报405错误，因为原方法的属性被移除了，加在了新方法上，而请求进来调用的是原方法名。

请问这个可以通过配置或者某个属性来实现不改变原方法的属性吗？

**Comment by inversionhourglass** [comment]
你用的版本是`3.0.x`，这个反馈过（ #75 ），已经修复了，更新到`3.1.0`以上就可以了，推荐直接更新到`4.0.0`

**Comment by josephgugu** [comment]
多谢。问题解决了
