### ISSUE TITLE
关于3.0以上版本在net8环境下进入调试后无法查看方法内任何变量对象的问题

### ISSUE THREAD

**Issue by hchxxzx** [inversionhourglass/Rougamo#77]
Rougamo非常不错！简直太符合我的胃口了，简单明了，功能强大。感谢作者的心血投入。
这几天在做各种测试，目前发现一个问题，全网找来找去，还好找到这里了。
刚刚看了你的3.0版的文章，里面说2.0版本不支持步入调试，3.0以后支持了。
但这和我碰到的问题差别有点大。
我碰到的问题是：在4.0版本下，代码可以正常进入事务，但在具体的方法内部，所有的对象、变量的值均无法查看，调试仍然可以一步一步往下走，但如果各个对象的状态、值看不到，那这个调试就毫无意义。
经过一个版本一个版本测试，发现：3.0以下的版本，可以正常调试，可以看到方法内部所有对象变量的值；但3.0以上，任何版本都不行。
我目前使用的是net8版本。或许我应该试试比如net6或者其他版本？
或者是我某个地方做得不对？但我上述测试均是在最简化条件下测试的结果。
还请赐教，谢谢！
我已提供了最简化的测试代码项目，可直接运行调试，地址如下：
https://gitee.com/hchxxzx/rougamotest

**Comment by inversionhourglass** [comment]
感谢反馈，我研究下，这个问题可能没那么快能解决

**Comment by inversionhourglass** [comment]
已修复，发布了预发版本 **4.0.1-preview-1725141430** ，你可以先试试，周一会发布正式版

**Comment by hchxxzx** [comment]
OK！我马上试试。

**Comment by hchxxzx** [comment]
可以了！太棒了！谢谢！
