### ISSUE TITLE
4.0.1 blazor webassembly 是否可以考虑支持

### ISSUE THREAD

**Issue by bxjg1987** [inversionhourglass/Rougamo#78]
blazor webassembly和auto模式中的客户端部分，使用的是WebAssemblyHost，它不是反省主机，
肉夹馍4.0.1目前测试没法在blazor webassembly中使用，这个可以加上吗

另外blazor的依赖注入跟asp.net core的依赖注入有差别，并且分server、webassembly和auto模式，参考：
https://learn.microsoft.com/zh-cn/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-8.0

**Comment by inversionhourglass** [comment]
好的，我研究下

**Comment by inversionhourglass** [comment]
已完成对Blazor的支持，可以参考博客：https://www.cnblogs.com/nigture/p/18412772#%E8%82%89%E5%A4%B9%E9%A6%8D%E7%9B%B8%E5%85%B3%E5%BA%94%E7%94%A8

或者直接参考示例项目：https://github.com/inversionhourglass/Rougamo.DI/tree/master/samples

之后如果有依赖注入相关的问题，可以到 https://github.com/inversionhourglass/Rougamo.DI 中提交issue

**Comment by bxjg1987** [comment]
好的，感谢哈！
