### ISSUE TITLE
WPF中按钮绑定ICommand时使用 await/async 异常无法正确被处理

### ISSUE THREAD

**Issue by 2876** [inversionhourglass/Rougamo#8]
版本：1.1.0-alpha1
在WPF中使用MVVM模式
关键代码：
View:
`
<Button
            Command="{Binding TestCommand}"
            Content="Button" />
`
ViewModel:
```
public class ViewModel : VmBase
    {
        public RelayCommand TestCommand => new RelayCommand(async o =>await Command());

        [Log]
        private async Task Command()
        {
            await Task.Delay(500);
            throw new Exception("1231232");
        }
    }
```
```
 [AttributeUsage(AttributeTargets.Method)]
    public sealed class LogAttribute : Rougamo.MoAttribute
    {
        public override void OnEntry(MethodContext context)
        {

        }
        public override void OnException(MethodContext context)
        {
            context.HandledException(this, null);
        }
        public override void OnExit(MethodContext context)
        {

        }
        public override void OnSuccess(MethodContext context)
        {

        }
    }
```
  OnException方法正常触发，但异常未被处理，还会抛出导致程序关闭。
异常如下：
System.Exception
  HResult=0x80131500
  Message=1231232
  Source=WpfApp1
  StackTrace:
   at WpfApp1.ViewModel.<Command>d__2.MoveNext() in F:\Rougamo\src\WpfApp1\MainWindow.xaml.cs:line 31
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WpfApp1.ViewModel.<<get_TestCommand>b__1_0>d.MoveNext() in F:\Rougamo\src\WpfApp1\MainWindow.xaml.cs:line 25

  此异常最初是在此调用堆栈中引发的: 
    WpfApp1.ViewModel.Command() (位于 MainWindow.xaml.cs 中)
    [外部代码]
    WpfApp1.ViewModel.get_TestCommand.AnonymousMethod__1_0(object) (位于 MainWindow.xaml.cs 中)

**Comment by inversionhourglass** [comment]
看了下这个问题，这个是异常处理后的代码没有织入导致的，白天还有些其他工作，没有太多时间去解决这个，预计晚上回去能解决这个问题

**Comment by inversionhourglass** [comment]
发布了 `1.1.0-alpha2` ，你更新了再试试，如果有其他问题可以再提issue

**Comment by 2876** [comment]
> 发布了 `1.1.0-alpha2` ，你更新了再试试，如果有其他问题可以再提issue
问题已解决，谢谢~
但是还有两个小问题，因为跟该issue密切相关，就在这里提出
1：
'''
[Log]
        private **async void** Command()
        {
            await Task.Delay(500);
            throw new Exception("1231232");
        }
'''
当async Task 改为asyn void时，上述context.HandledException方法会报错：System.InvalidOperationException:“序列不包含任何元素”
2：
'''
[Log]
        private void Command()
        {
            throw new Exception("1231232");
        }
'''
直接在方法里抛出异常会导致编译不通过~

**Comment by inversionhourglass** [comment]
`1.1.0-alpha3` 你更新了再试试

**Comment by 2876** [comment]
这个OK了，已经可以用了~
可是还有点问题  
```
public class ViewModel : VmBase
    {
        public RelayCommand TestCommand => new RelayCommand(async o =>await Command());

        [Log]
        private void Command()
        {
            await Task.Delay(500);
            throw new Exception("1231232");
        }
    }
```
WPF命令绑定中，只要在被特性标记的方法体中直接抛出异常（Log内处理了异常），async o =>await Command()会引发异常System.InvalidProgramException:“公共语言运行时检测到无效的程序。”  但若在嵌套方法中抛出异常则能正确处理。
![微信截图_20220624155101](https://user-images.githubusercontent.com/51232529/175489562-6dc5e4f8-ae91-4e00-8ebe-5f6ba66ada1f.png)
具体异常见附件截图。

**Comment by inversionhourglass** [comment]
没写过WPF，`RelayCommand` 接收的参数类型是什么，是`Func<object, Task>`？你贴的代码和截图里的代码有些区别，是`new RelayCommand(async o =>await Command())` 和 `new RelayCommand(o =>Command())` 都会出现异常是吗

**Comment by 2876** [comment]
对不起，代码贴错了，以截图为准。
RelayCommand接受的参数为Action<object>
异步方法不会出现异常，只有同步方法会出现（即截图上方法）
我已把项目测试代码打包，见附件
[WpfApp1.zip](https://github.com/inversionhourglass/Rougamo/files/8974954/WpfApp1.zip)
。

**Comment by inversionhourglass** [comment]
修复发布了`1.1.0-alpha4`，1.1.0的代码自从上次写完了，还没怎么写测试代码，你这一系列反馈算是帮大忙了

**Comment by 2876** [comment]
可以用了，谢谢
