### ISSUE TITLE
可以在父类设置 Attribute后，子类同样生效吗？ 如何设置？

### ISSUE THREAD

**Issue by food4321** [inversionhourglass/Rougamo#80]

**Comment by inversionhourglass** [comment]
哪种设置？类似`Flags`, `Features`的这种属性，还是`OnEntry`, `OnEntry`这种方法？这些都支持，正常C#代码怎么写就怎么写。

建议啊，这种问题先自己正常写代码尝试，有问题了再提问。没有上手尝试，直接提出问题然后等待结果是不好的习惯

**Comment by food4321** [comment]
**就是类似这种，在父类中设置LogAttribute:MoAttribute**
``` c#
    [Log] //父类设置LogAttribute
    public class ParentForm : Form
    {
    }

    public class Form1 : ParentForm
    {
        //测试子类，AOP 拦截
        public void TestLog()
        {
        }
    }
```
**还有几个其他问题**
1. 解决方案中有多个项目的情况，需要每一个都要静态引用 Rougamo 吗？
2. 每一个子项目都会生成 **FodyWeavers.xsd**，**FodyWeavers.xml** 2个文件， 有办法只在一个地方生成吗？例如公共类生成一个

**Comment by inversionhourglass** [comment]
> 就是类似这种，在父类中设置LogAttribute:MoAttribute
Attribute不支持继承，但是你可以使用空接口`IRougamo<>`，比如你上面的代码改成`public class Form1 : ParentForm, IRougamo<LogAttribute>`，详情查看文档 [实现空接口IRougamo](https://github.com/inversionhourglass/Rougamo/wiki/%E5%BA%94%E7%94%A8%E6%96%B9%E5%BC%8F#%E5%AE%9E%E7%8E%B0%E7%A9%BA%E6%8E%A5%E5%8F%A3irougamo)

> 解决方案中有多个项目的情况，需要每一个都要静态引用 Rougamo 吗？
有用到Rougamo的功能就需要直接引用，或者参考 [如何让其他人在引用你的包后不再需要直接引用肉夹馍](https://github.com/inversionhourglass/Rougamo/wiki/%E5%85%B6%E4%BB%96#%E4%BD%BF%E7%94%A8%E8%82%89%E5%A4%B9%E9%A6%8D%E5%BC%80%E5%8F%91%E4%B8%AD%E9%97%B4%E4%BB%B6%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

> 每一个子项目都会生成 FodyWeavers.xsd，FodyWeavers.xml 2个文件， 有办法只在一个地方生成吗？例如公共类生成一个
这个问题别人已经回复过你了，https://github.com/inversionhourglass/Rougamo/issues/26#issuecomment-2333641211 ，不要懒得看，里面有提到两种方式，你想要的应该是第二种“将FodyWeavers.xml放到解决方案目录”

**Comment by food4321** [comment]
> Attribute不支持继承，但是你可以使用空接口`IRougamo<>`，比如你上面的代码改成`public class Form1 : ParentForm, IRougamo<LogAttribute>`，详情查看文档 [实现空接口IRougamo](https://github.com/inversionhourglass/Rougamo/wiki/%E5%BA%94%E7%94%A8%E6%96%B9%E5%BC%8F#%E5%AE%9E%E7%8E%B0%E7%A9%BA%E6%8E%A5%E5%8F%A3irougamo)

如果优先编译工具类，然后在编译项目可以正常工作，但是整体重新编译，或者整体编译就会出现以下错误。
```kljlh
MSBUILD : error : Fody: An unhandled exception occurred:
MSBUILD : error : Exception:
MSBUILD : error : Failed to execute weaver D:\01.project\XZ\SZXZ_MES_Client_Src\packages\Rougamo.Fody.4.0.1\build\..\weaver\Rougamo.Fody.dll
MSBUILD : error : Type:
MSBUILD : error : System.Exception
MSBUILD : error : StackTrace:
MSBUILD : error :    在 InnerWeaver.ExecuteWeavers() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 219
MSBUILD : error :    在 InnerWeaver.Execute() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 106
MSBUILD : error : Source:
MSBUILD : error : FodyIsolated
MSBUILD : error : TargetSite:
MSBUILD : error : Void ExecuteWeavers()
MSBUILD : error : 未将对象引用设置到对象的实例。
MSBUILD : error : Type:
MSBUILD : error : System.NullReferenceException
MSBUILD : error : StackTrace:
MSBUILD : error :    在 Fody.CecilExtensions.GetSequencePoint(MethodDefinition method) 位置 C:\projects\fody\FodyHelpers\CecilExtensions.cs:行号 7
MSBUILD : error :    在 Fody.BaseModuleWeaver.WriteError(String message, MethodDefinition method) 位置 C:\projects\fody\FodyHelpers\BaseModuleWeaver.cs:行号 123
MSBUILD : error :    在 Fody.SimulationModuleWeaver.Execute()
MSBUILD : error :    在 InnerWeaver.ExecuteWeavers() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 179
MSBUILD : error : Source:
MSBUILD : error : FodyHelpers
MSBUILD : error : TargetSite:
MSBUILD : error : Mono.Cecil.Cil.SequencePoint GetSequencePoint(Mono.Cecil.MethodDefinition)
MSBUILD : error : 
```

> 这个问题别人已经回复过你了，[#26 (comment)](https://github.com/inversionhourglass/Rougamo/issues/26#issuecomment-2333641211) ，不要懒得看，里面有提到两种方式，你想要的应该是第二种“将FodyWeavers.xml放到解决方案目录”

这个我在留言 时候没看到，我去试一下

**Comment by inversionhourglass** [comment]
这个异常信息你双击应该能定位到出现问题的方法上，方便的话提供一下对应方法的代码，或者可以复现该问题的简化代码，如果代码比较多，可以上传到github然后贴个链接

**Comment by food4321** [comment]
> 这个异常信息你双击应该能定位到出现问题的方法上，方便的话提供一下对应方法的代码，或者可以复现该问题的简化代码，如果代码比较多，可以上传到github然后贴个链接

知道问题了，如果父类中 存在如下代码就会报错
```
  [DllImport("user32.dll")]
  private static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
```
有办法，全局忽略 Windwos API 函数吗？

**Comment by inversionhourglass** [comment]
暂时没有全局忽略的方式，目前最简单的方法是在这个方法上增加`[IgnoreMo]`，这种方法本身无法通过.NET代码进行AOP操作，后续会直接忽略掉这种方法

**Comment by food4321** [comment]
好的，谢谢

**Comment by inversionhourglass** [comment]
不行的，肉夹馍是编译时AOP组件，他拿到的都是开发人员写的代码的元数据，并不能直接执行开发人员所写的代码。

其实肉夹馍本身已经拥有了很好的精细的方法筛选控制，可以了解一下 [类AspectJ表达式匹配](https://github.com/inversionhourglass/Rougamo/wiki/%E6%96%B9%E6%B3%95%E5%8C%B9%E9%85%8D#%E7%B1%BBaspectj%E8%A1%A8%E8%BE%BE%E5%BC%8F%E5%8C%B9%E9%85%8D) 。本来我一开始是准备回复你，让你把`LogAttribute`改成下面这样：
```csharp
public class LogAttribute : MoAttribute
{
    public override string? Pattern => "method(* *(..)) && !attr(exec DllImportAttribute)";
}
```
上面这段表达式的含义是“匹配所有普通方法（非属性），且方法的Attribute中不包含`DllImportAttribute`”，不过我刚好有空试了下，无法匹配到目标方法，这并不是因为这种方式有问题，而是因为这种P/Invoke方法上的`DllImportAttribute`在编译时会被编译器删掉并转换为一个特殊的方法元数据（你可以自己尝试反编译看看IL），所以`!attr(exec DllImportAttribute)`无法奏效

**Comment by food4321** [comment]
> 已发布4.0.2，默认忽略windows api方法

好的 谢谢
