### ISSUE TITLE
多维数组 声明后报错

### ISSUE THREAD

**Issue by food4321** [inversionhourglass/Rougamo#81]
```
 [Log]
 private void LoadData()
 {
     string[,] values = new string[1, 1];
 }
```

**Comment by inversionhourglass** [comment]
收到，感谢反馈，稍后修复

**Comment by inversionhourglass** [comment]
感谢反馈，之前的测试用例只覆盖了交错数组形式的多维数组`int[][]`，没有覆盖到矩形数组`int[,]`

已发布预发版`4.0.3-preview-1725957423`，先用预发版吧，下周发布正式版，需要控制版本频率

**Comment by food4321** [comment]
好的，辛苦了

**Comment by food4321** [comment]
实在不好意思，无意间又发现一个问题。
以下代码也会报错，这是什么问题呢？
``` c#
[Log]
public void TestThrow()
{
    try
    {
        throw new Exception("test");
    }
    catch (Exception)
    {

        throw;
    }            
}
```

**Comment by food4321** [comment]
这个配置现在是有的吗？

      默认使用3.0版本的代理调用织入方式，可通过配置修改织入方式

（配置的方式为修改`FodyWeavers.xml`文件中的配置）

_Originally posted by @inversionhourglass in https://github.com/inversionhourglass/Rougamo/issues/68#issuecomment-2094667061_

**Comment by inversionhourglass** [comment]
> 实在不好意思，无意间又发现一个问题。

感谢反馈，没什么不好意思的，更全面的测试用例都靠你们来反馈。不过建议不同的问题新建一个issue进行反馈

**Comment by inversionhourglass** [comment]
> 这个配置现在是有的吗？

4.0版本开始就不支持了，这个只是3.0版本的过渡配置。内联织入在未使用`async/await`语法的方法处理上容易让人误解，你可以看一下我3.0版本的博客 [不同织入方法带来的影响](https://www.cnblogs.com/nigture/p/18173550#%E4%B8%8D%E5%90%8C%E7%BB%87%E5%85%A5%E6%96%B9%E6%B3%95%E5%B8%A6%E6%9D%A5%E7%9A%84%E5%BD%B1%E5%93%8D)
