### ISSUE TITLE
a mode suggest

### ISSUE THREAD

**Issue by gonggonggnog** [inversionhourglass/Rougamo#87]
是否考虑加一个模式，返回的Methodbase是带$Rougamo_的原始方法，而不是IL之后的呢

**Comment by inversionhourglass** [comment]
这个建议可以加，可以在`MethodContext`中额外增加一个属性，不过需要注意的是，原方法上的Attribute等信息都转移到代理方法，方法部分元数据会有所变化，使用时需要注意。

另外了解一下，你需要原方法的`MethodBase`的使用场景是什么。

**Comment by gonggonggnog** [comment]
谢谢。
因为是winform项目并且些许陈旧，页面按钮事件都是同步实现的，我想在一些函数上用异步加窗口的形式包裹整个原方法，如果是现在的MethodBase去使用的话，会反复回调编织后的方法，这将会导致无限递归

**Comment by inversionhourglass** [comment]
明白你的使用场景了。不过我又想了一下，肉夹馍一直在各个方面进行着性能优化，包括现有结构体支持以及瘦身`MethodContext`封，下一个大版本将再提供更多的性能优化方案。基于性能优化考虑，肉夹馍所以还是会尽量避免增加新的成员，所以你考虑一下下面的这个方案。

由于原方法的方法名固定为$Rougamo_前缀，所以可以简单的通过名称反射从`MethodConext.TargetType`中获取原方法。
