### ISSUE TITLE
对 .NET 9 Blazor 组件构造函数注入的支持

### ISSUE THREAD

**Issue by ElderJames** [inversionhourglass/Rougamo#88]
作者你好，我看到这个项目对Blazor的DI有很好的改进。

在.NET 9 的Blazor组件支持构造函数注入之后，我觉得还可以再次改进，使侵入性更低。也许目前已经支持这种方式而我不了解的，但我想请教下我的思路是否可行，并且目前用Rougamo如何支持。

比如一个组件，有个按钮点击事件绑定 `Save` 方法，调用MyDbContext 来更新。

```cs
public partial class MyComponent(MyDbContext db): ComponentBase
{
        private List<Data> _list;
         public async Task Save()
         { 
               var data = new Data{};
                db.Data.Add(data);
                await  db.SaveChangesAsync();
                await this.reload();
         }

        private async Task Reload()
        {
                 _list = await db.Data.ToListAsync();
        }
}
```

能在编译时变为在方法中重新获取当前类型的实例，这样依赖注入的服务以及子服务都是当前scoped的，但对于实例内的方法（Reload方法）调用不再从依赖注入获取服务。这样就能解决soped作用域太短的问题，实现跨多方法的作用域了。

```cs
public partial class MyComponent(MyDbContext db): ComponentBase
{
        private  List<Data> _list;
         public async Task Save()
         { 
                var component = ServiceProvider.GetService<MyComponent>();
               await component.Save(); 
                _list= component._list;
         }

        private async Task Reload()
        {   
                   var component = ServiceProvider.GetService<MyComponent>();
                  _list = await component.Reload();
        }
}
```

最后还需要映射字段，把新实例的 _list 字段映射出来

**Comment by inversionhourglass** [comment]
你好，没太明白你的意思。

> 能在编译时变为在方法中重新获取当前类型的实例，这样依赖注入的服务以及子服务都是当前scoped的

是指`var component= ServiceProvider.GetService<MyComponent>();`吧，但一般情况下，这里获取到的`MyComponent`实例与当前的`MyComponent`是同一个实例，当然，如果你的`ServiceProvider`不是从当前scope中取得的情况除外。

> 但对于实例内的方法（Reload方法）调用不再从依赖注入获取服务

根据你的代码，`repository`实例就是来自依赖注入的，不太明白你的意思。

> 这样就能解决soped作用域太短的问题，实现跨多方法的作用域了。

对于“scoped作用域太短”和“跨多方法作用域”的含义也不太理解，作用域短的表现是什么样的，跨多方法作用域是指第一段代码中`Save`中调用`reload`方法这种跨多方法？

你上面提供的两段代码不方便联合理解，第一段使用`DbContext`第二段使用`Repository`，另外第一段中在`Save`方法中调用了`reload`方法，应该是手误吧，大小写输入错了，第二段代码中`Save`方法没有调用`Reload`方法，两段代码合在一起无法关联起来。

**Comment by inversionhourglass** [comment]
没事，我就是没太明白你的意思，希望你重新描述一下。

对于你说的这种“scoped作用域太短”的问题，你希望的“跨多方法作用域”是什么样的，跨多个回调事件还是什么。据我所知，blazor server中依赖注入的服务生命周期很长，是整个signalR连接的生命周期，针对你的需求这个生命周期是又太长了吗。

你希望了解肉夹馍能够实现什么样的功能，方便的话可以重新描述一下你的具体需求吗

**Comment by ElderJames** [comment]
我就希望肉夹馍可以实现Blazor组件的方法拦截，能在事件绑定方法之间增加一层代理，并且实现在这个方法调用前创建一个scope，用这个scope实例化当前组件，调用同名的方法，然后状态（字段和属性）同步回当前的组件。

**Comment by inversionhourglass** [comment]
大概明白你的意思了，你看看理解的对不对

> 让用户用默认的注入方式，但实际上还是方法级别的ScopeServiceProvider

这个应该是你的主要目的了，默认的注入方式注入的服务的生命周期太长，你希望借助肉夹馍让默认注入方式注入的服务能够拥有一个短的生命周期，也就是事件回调方法创建的生命周期。

如果是这个需求的话，不太建议通过新建scope再次创建component，状态同步不好做，特别是双向状态同步。我有另外一个思路，你看看时候合适。

自定义一个肉夹馍切面Attribute，应用了该Attribute的属性在get时将从事件回调方法的scope中获取实例。
```csharp
public partial class MyComponent : PinnedScopeOwningComponentBase
{
    [ScopedInject]  // 先聊思路，确定了再聊具体实现
    public IMyService MyService { get; }

    public async Task Save()
    {
        await MyService.SaveAsync();
    }
}
```

如果上面理解没错的话，我还有一个疑问，跨多方法作用域怎么理解。按照你的思路，即使实现了，scope的声明周期依然是时间回调的方法。

**Comment by ElderJames** [comment]
我说的跨方法的意思是，多个方法中用到的服务应该在同一个作用域中。在一般的WebAPI无状态应用中，一个请求就是一个scope，所以这个请求中的所有服务、所有跨方法的调用，都是同一个实例，除非用户自己另外创建scope和瞬时服务。

还有一个场景比较常见的，就是EFCore的实体跟踪，unit of work 等等，可以在多个方法中进行多次的查询、变更，然后一次性的SaveChanges，以达到减少变更和事务性的目的。

而如果在blazor server中，调用DbContext的方法都被要求用DbContextFactory创建DbContext示例，一个方法完成查询和更新，不能用多个方法查询后一起更新（因为每个方法都是新的实例，方法返回数据后就无法跟踪了），这是我想通过AOP解决的。

**Comment by inversionhourglass** [comment]
你在issue最开始的表述有点混乱，没能理解，不过既然确定我前面说的方案基本可行，那就接着这个方案聊。

> 如果能免去PinnedScopeOwningComponentBase这个基类就好了

在.NET 8及之前可以在`_Imports.razor`设置所有component的基类，这样就能极大程度减少侵入了，不过看你上面提供的代码，.NET 9应该是不支持`_Imports.razor`了。这样的话就无法避免要实现自定义基类了，`OwningComponentBase`提供的`ScopedServices`属性以及`Rougamo.DI`提供的DI扩展是必不可少的部分。

> 拦截[Inject]特性或者构造函数的注入服务

两种情况需要分开说：

1. **拦截[Inject]特性**

    从技术上来说是可以实现的，肉夹馍支持 [Attribute代理织入](https://github.com/inversionhourglass/Rougamo/wiki/%E5%BA%94%E7%94%A8%E6%96%B9%E5%BC%8F#attribute%E4%BB%A3%E7%90%86)，但不推荐。因为被[Inject]标注的属性是在外部完成实例化再赋值给该属性的，拦截无法取消外部的实例化操作，这样会导致外部创建的实例在创建后就直接宣布死亡，增加GC负担，特别是这个类型还通过构造方法注入了一系列其他服务的情况。

2. **拦截构造函数的注入服务**

    这个从技术上来说就是无法实现的，`OwningComponentBase.ScopedServices`依赖于[Inject]注入的`ScopeFactory`，而[Inject]注入是发生在构造方法执行完之后，所以构造方法中是无法使用`ScopedService`的。另外在构造方法中也无法做到为每个事件回调方法单独创建一个scope，因为component由SignalR所属scope创建，在构造方法中创建scope约等于使用SignalR所属scope

**Comment by inversionhourglass** [comment]
我那个方案的基本实现我先贴出来吧。

1. **NuGet包**

    - Rougamo.Fody
    - Rougamo.Extensions.DependencyInjection.Microsoft
    - DependencyInjection.StaticAccessor.Blazor

2. **定义ScopedInjectAttribute**

    ```csharp
    [AttributeUsage(AttributeTargets.Property)]
    public class ScopedInjectAttribute : MoAttribute
    {
        public override Feature Features => Feature.EntryReplace;

        public override void OnEntry(MethodContext context)
        {
            var service = context.GetRequiredService(((MethodInfo)context.Method).ReturnType);

            context.ReplaceReturnValue(this, service);
        }
    }
    ```

3. **初始化DependencyInjection.StaticAccessor**

    ```csharp
    var builder = WebApplication.CreateBuilder(args);

    // 初始化DependencyInjection.StaticAccessor
    builder.Host.UsePinnedScopeServiceProvider();

    var app = builder.Build();

    app.Run();
    ```

4. **相关页面（Component）继承PinnedScopeOwningComponentBase**

    推荐在`_Imports.razor`中直接声明，如果`_Imports.razor`可以用的话。

5. **使用ScopedInjectAttribute**

    对需要注入的属性应用`[ScopedInject]`，或在当前程序集任意地方应用`[assembly: MoProxy(typeof(InjectAttribute), typeof(ScopedInjectAttribute))]`，达到使用`ScopedInjectAttribute`拦截`InjectAttribute`的目的（不推荐）。

**Comment by ElderJames** [comment]
@inversionhourglass 你好，我再想了一下，我觉得可以结合Source Generators来先生成一些基础代码，然后用AOP拦截改写原方法的执行。

首先，SG根据组件中定义的方法，生成一个代理对象，这个代理对象拥有所有字段、属性和方法，另外还有一个方法用于状态同步。
然后AOP帮忙修改事件绑定的那个方法，从IoC中创建Scope并获取这个代理对象，然后同步当前组件的状态到代理对象，执行这个方法，然后再将代理对象状态同步回当前组件。

不知道Rougamo如何拦截和执行SG生成的方法？

**Comment by inversionhourglass** [comment]
1. 定义切面类型

    ```csharp
    public class XAttribute : MoAttribute
    {
        public override Feature Features => Feature.EntryReplace;
    
        public override void OnEntry(MethodContext context)
        {
            // 由于不希望页面继承PinnedScopeOwningComponentBase，这里就不使用Rougamo.DI扩展方法，如何获取IServiceProvider对象需要自己考虑了，这里假设所有页面都实现IServiceProviderHolder接口
            if (context.Target is not IServiceProviderHolder holder) return;
    
            var serviceProvider = holder.ServiceProvider;
            var proxyType = context.TargetType.Assembly.GetType($"{context.TargetType.FullName}_Proxy");
            var proxyInstance = serviceProvider.GetRequiredService(proxyType);
    
            // 假设Source Generators生成的类型都实现IStateSyncable接口，包含Sync方法用于同步状态
            ((IStateSyncable)proxyInstance).Sync(context.Target);
    
            var proxyMethod = proxyType.GetMethod(context.Method.Name);
            var result = proxyMethod.Invoke(proxyInstance, context.Arguments);
    
            context.ReplaceReturnValue(this, result);
        }
    }
    ```

2. 将切面类型应用到事件方法

    最简单的方式就是在每个事件方法上应用`XAttribute`，如果觉得侵入性太大，这里给出一种参考方式，比如所有事件的方法名都以On开头，可以在项目任意位置应用以下代码：
    ```csharp
    // pattern的含义是：ComponentBase子类所有名称以On开头的方法
    [assembly: X(Pattern = "method(* ComponentBase+.On*(..))")]
    ```
    如果感觉上面的方式不合适，可以在 [应用方式文档](https://github.com/inversionhourglass/Rougamo/wiki/%E5%BA%94%E7%94%A8%E6%96%B9%E5%BC%8F) 中寻找一个适合自己的方式。

**以上代码均为浏览器手敲代码，不一定能直接运行，需要根据实际情况再做调整。**

**Comment by ElderJames** [comment]
谢谢，请问这里会用到反射吗，还是说编译时自动变为直接调用？

另外请问下什么时候可以升级一下.NET 9，我希望在.NET 9中使用，包括依赖注入的类库

**Comment by ElderJames** [comment]
[BlazorApp1.zip](https://github.com/user-attachments/files/17929651/BlazorApp1.zip)
我写好了SG，ServiceProvider的获取也解决了。我觉得里面生成的proxy类可以直接改为生成MoAttribute，只是每个方法生成一个MoAttribute 的话，不知道如何匹配到对应的方法上。

**Comment by inversionhourglass** [comment]
> 只是每个方法生成一个MoAttribute 的话，不知道如何匹配到对应的方法上

由于已经知道对应的方法的名字了，AspectN表达式就很好写了，设置好Pattern直接将Attribute应用到程序集就可以了
```csharp
[assembly: WeatherInternal_OnInitializedAsync]

public class WeatherInternal_OnInitializedAsyncAttribute : MoAttribute
{
    public override string Pattern => "method(* Weather.Internal_OnInitializedAsync(..))";

    public override void OnEntry(MethodContext context)
    {
        if (context.Target is not Weather target) return;

        var serviceProvider = target.GetServiceProvider();
        using var scope = serviceProvider.CreateScope();
        var newTarget = scope.ServiceProvider.GetRequiredService<Weather>();
        newTarget.SyncState(target); 

        await newTarget.Internal_OnInitializedAsync();

        target.SyncStateBack(newTarget); 
    }
}
```

根据你的设计，推荐同步方法继承`MoAttribute`重写`OnEntry`，异步方法继承`AsyncMoAttribute`重写`OnEntryAsync`，比如你上面的例子适合继承`AsyncMoAttribute`。
```csharp
public class WeatherInternal_OnInitializedAsyncAttribute : AsyncMoAttribute
{
    public override string Pattern => "method(* Weather.Internal_OnInitializedAsync(..))";

    public override async ValueTask OnEntry(MethodContext context)
    {
        if (context.Target is not Weather target) return;

        var serviceProvider = target.GetServiceProvider();
        using var scope = serviceProvider.CreateScope();
        var newTarget = scope.ServiceProvider.GetRequiredService<Weather>();
        newTarget.SyncState(target); 

        await newTarget.Internal_OnInitializedAsync();

        target.SyncStateBack(newTarget); 
    }
}
```

**Comment by ElderJames** [comment]
感谢指导，我试试看 @inversionhourglass
