### ISSUE TITLE
为什么不支持.net framework?

### ISSUE THREAD

**Issue by byrybye** [inversionhourglass/Rougamo#89]
我需要一个支持 .net framework 的版本， 4.8 的就行，谢谢！这个库非常好，但是我现在只能使用 MethodBoundaryAspect，希望能尽快支持.net framework，谢谢！

**Comment by inversionhourglass** [comment]
支持的啊，肉夹馍是.NET Standard 2.0，最低兼容.NET Framework 4.6.1

**Comment by inversionhourglass** [comment]
nuget是老格式的packages.config还是新格式的PackageReference。如果是老格式，先升级。

升级后或本来就是新格式的，确定Rougamo.Fody在未生效项目是否正常通过nuget引用，而不能是文件引用。

**Comment by NewOnePerson** [comment]
我用ILSpy分别看了运行时候的dll （有 AOP）跟发布之后的dll（无Aop）
![微信截图_20241114130553](https://github.com/user-attachments/assets/04b27eab-07d9-46a7-a940-18ace373ca10)
![微信图片编辑_20241114130458](https://github.com/user-attachments/assets/e22cf8a6-40c3-4175-9e92-e31172a796a7)
项目比较老 nuget有的无法升级成PackageReference 只有PackageReference 才能将发布的程序添加AOP吗

**Comment by inversionhourglass** [comment]
> 只有PackageReference 才能将发布的程序添加AOP吗

不是，但是packages.config存在很多问题。

你一开始描述的情况基本可以确定是没有正确依赖肉夹馍导致的，如果是PackageReference格式，那还比较好排查，但如果是packages.config，那就难说了。如果你就是packages.config，那我只能建议你手动删除packages.config以及项目文件(.csproj)中Rougamo.Fody相关内容并重新安装Rougamo.Fody依赖，这个也只是尝试修复，不能保证有效。

还是建议将packages.config迁移到PackageReference，packages.config问题太多，人迟早被坑麻了。迁移参考 https://learn.microsoft.com/zh-cn/nuget/consume-packages/migrate-packages-config-to-package-reference

**Comment by NewOnePerson** [comment]
收到，感谢回复
