### ISSUE TITLE
是否有办法可以判断方法由Http请求调用还是代码直接调用

### ISSUE THREAD

**Issue by Zzzzjle** [inversionhourglass/Rougamo#90]
作者您好，我正在研究 Blazor 的 SSR 模式下的异常处理，遇到了一些问题。

具体情况是这样的：我在客户端使用 Refit 定义了 HTTP 请求接口，同时后端的 Controller 继承了该接口。在 SSR 模式下，我通过依赖注入的方式直接调用后端的 Controller 方法；而在 CSR 模式下，客户端则通过 HTTP 请求调用后端接口。

目前在 CSR 模式下，接口如果抛出业务异常，我可以通过中间件对其进行统一处理。但在 SSR 模式下，我希望使用 AOP 实现异常处理。问题在于：
我希望 AOP 仅在代码直接调用 Controller 方法（即 SSR 模式）时处理异常，而当方法是通过 HTTP 请求调用时，异常则无需处理。

请问是否有办法判断一个方法是由 HTTP 请求调用，还是由代码直接调用？

**Comment by inversionhourglass** [comment]
这个看起来不是一个肉夹馍的问题，这个问题可以简化为如何在 Controller 方法中判断本次调用是本地调用还是HTTP调用。

如果你在 Controller 方法中有办法判断，你可以贴出来，我给你一个对应到肉夹馍中的解决方案。

如果你暂时还没有办法判断，你提供一下代码，我具体看看。虽然你描述的比较清晰，不过我没写过 Blazor，还是需要根据实际代码来分析。

**Comment by Zzzzjle** [comment]
在 Controller 的方法中可以通过 HttpContext 是否为空来判断

**Comment by inversionhourglass** [comment]
```csharp
public class TestAttribute : MoAttribute
{
    public override void OnEntry(MethodContext)
    {
        if (context.Target is not Controller controller || controller.HttpContext != null) return;
    }
}
```

其他几个切面方法（OnSuccess, OnException, OnExit）也需要判断

**Comment by Zzzzjle** [comment]
问题解决了，感谢作者💐
