### ISSUE TITLE
子类，打上 aop 标记后 无法拦截 父类中的函数或者属性

### ISSUE THREAD

**Issue by hzy-6** [inversionhourglass/Rougamo#92]
<img width="556" alt="image" src="https://github.com/user-attachments/assets/d1890514-61e4-4ec3-bc9e-0dbea8685fce">

**Comment by hzy-6** [comment]
能否加一个属性开关，这样需要的就开启，我需要实现一个 类似 springboot ConfigurationProperties 的特性

**Comment by hzy-6** [comment]
或者能否让拦截器触发执行一下，这样我可以通过 class 的实例，做一些操作

**Comment by hzy-6** [comment]
特性打在类上，不能触发默认构造，我现在只能手动设置到 构造上面来实现这个功能。感觉不太好

**Comment by inversionhourglass** [comment]
> 能否加一个属性开关，这样需要的就开启

这个不是开关的问题，这是父类如果跟子类不在同一个程序集就做不了

> 或者能否让拦截器触发执行一下

触发执行时指什么，触发父类所在程序集执行肉夹馍的逻辑吗？这个就更做不了了，父类都不一定是项目引用，可能来自三方包，这种情况都不会经过编译。

> 特性打在类上，不能触发默认构造

是指默认构造方法吗，可以试试`EmptyConstructor.Fody`，这个好像是会帮你生成默认构造方法的

**Comment by hzy-6** [comment]
<img width="677" alt="image" src="https://github.com/user-attachments/assets/553bf2fa-86d7-41f6-b885-e431ddcd5fbe">
简化这个操作也可以

**Comment by hzy-6** [comment]
有案例吗？

**Comment by inversionhourglass** [comment]
我一会儿试试吧，我也没用过`EmptyConstructor.Fody`，这只是记得有这个，没用过。

**Comment by hzy-6** [comment]
这个功能，能加到下一个版本吗？默认，在构造函数植入拦截代码。这样实现就媲美 springboot 的 ConfigurationProperties

**Comment by inversionhourglass** [comment]
你说的这个默认是啥意思，`PointcutAttribute`匹配表达式也不配置吗。

**Comment by inversionhourglass** [comment]
> 有案例吗？

我试了一下，就你现在的代码，直接在`TestEntity1`所在程序集引用`EmptyConstructor.Fody`就可以了，他会为当前程序集所有类型添加默认无参构造方法（如果没有的话）。

另外，由于你主要匹配无参构造方法，上面的表达式改为`ctor(*())`更合适。

**Comment by hzy-6** [comment]
我做了兼容，出现这种跨程序集的，我才会打标记 到 构造函数上。否则走的都是拦截函数

**Comment by hzy-6** [comment]
有点小小的缺陷，我暂时还是手动打标记到 构造函数上

**Comment by inversionhourglass** [comment]
不对不对，老哥，你没做测试啊，连`EmptyConstructor.Fody`都不需要引用。默认构造函数在编译时会自动生成，你在你的`ConfigurationPropertiesAttribute`上应用`Pointcut("ctor(*())")`就直接可以了。

**Comment by hzy-6** [comment]
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/16aac02c-0451-4ac5-bed1-77873e99d334">
是这里面的一个属性吗

**Comment by inversionhourglass** [comment]
好吧，你没有升级 5.0，`PointcutAttribute`是 5.0 的类型，对应到之前的版本就是你截图里的 `Pattern`属性。但是 4.0 不支持`ctor`表达式。不升级肉夹馍的情况下，你可以重写`Flags`属性，改成下面这样：
```csharp
public override AccessFlags Flags => AccessFlags.Public | AccessFlags.Constructor;
```

不过还是推荐更新到 5.0 版本，提供了很多新的优化。可以查看 [Release Page](https://github.com/inversionhourglass/Rougamo/releases/tag/v5.0.0) 或者 [博客](https://www.cnblogs.com/nigture/p/18593689) 了解全部更新内容。

**Comment by hzy-6** [comment]
我试试 5.0

**Comment by inversionhourglass** [comment]
> 上线项目 k8s 配置信息需要读取环境变量 所以临时写这么一个插件，我担心 5.0 有不可预估的问题，导致服务故障

可以理解，线上稳定最重要，你按我上面给出的方式重写`Flags`也可以实现，可以观察后续小版本更新情况确定稳定情况再决定是否升级 5.0
