### ISSUE TITLE
Change the nuget package icon to Rougamo

### ISSUE THREAD

**Issue by tonyqus** [inversionhourglass/Rougamo#93]
I think this picture looks nice

![image](https://github.com/user-attachments/assets/b574e12b-52ae-4995-9656-21facd19dc7a)

**Comment by inversionhourglass** [comment]
Thank you. However, it's a bit too realistic for a NuGet package icon. If I ever become a Rougamo vendor, it would make a great promotional photo.

**Comment by tonyqus** [comment]
Fine
